---
title: "The critical minutiae (or the administrative slog of setting up a new company), Part 1"
author: "Byran Dai"
date: 2018-01-04
categories: ["daivergent"]
tags: ["incorporation","documentation","daivergent"]
summary: "There's always another form and fee to pay."
---

This is the part of the story that doesn't get shared often. You don't usually hear the courageous startup founder extol about how they successfully secured low rates on state unemployment insurance. There aren't a lot of feel-good stories about successfully filing Form 2553 with the IRS electing your new company as an S-Corp.

This is intended to be a short and sweet post of what I've had to do so far to set up this company, roughly in chronological order. I put it as a "Part 1" because I thought it would be interesting to lend some transparency into what the tangible steps I took so far to set up a company have looked like. YMMV and this experience should not be taken as a universal model, but I hope some insight can be gleaned from what has felt like a never-ending conveyor belt of forms to fill and fees to pay:  <br><br/>

  - Incorporated in Delaware as a Public Benefit Corporation
  - Registered for an EIN
  - Registered for a DUNS number for future contracting/sub-contracting opportunities
  - Completed New York State Employer Registration for Unemployment Insurance, Withholding, and Wage Reporting
  - Registered an account with SBA and set up an advisor with the SBDC in Harlem
  - Created a corporate website at [www.daivergent.com](www.daivergent.com)
  - Created numerous accounts with federal, state, city, and private contracting/sub-contracting sites (SAM, FBO, NYS Contract Reporter, NYC PassPort, and all the other acronyms)
  - Registered as a vendor with New York City to receive reimbursements for hiring adults with disability
  - Filed Form 2553 with the IRS
  - Requested a Certificate for Good Standing with the Delaware Secretary of State
  - Will then use the above certificate to submit an Application for Authority providing foreign qualification for my Delaware corporation to do business in New York State

This excludes the countless meetings, phone calls, meetups with friends and colleagues, emails (oh the emails), and non-stop reading online to make sure that every interaction I have is informed and productive. I'm recognizing why so many startups have co-founders in order to spread the work, and once I can clear time on my JIRA board, I think that'll be a crucial task for me to take on.

December 12, 2017. That's the day that Daivergent became a reality. It's amazing that as the third week comes to a close how much administrative hustling is still left, but the critical minutiae will wind down soon with the major first month hurdles finally out of the way.

I've made it my New Year's resolution to update and post more frequently, both for myself as well as for my friends, family, advisors, and new acquaintances that I've committed to keep up-to-date. Please don't hesitate to drop a line at bdai@daivergent.com, and keep an eye out for Part 2 as I enter into the second month of the administrative grind.