---
title: "Selling the idea"
author: "Byran Dai"
date: 2018-01-14
categories: ["early stage"]
tags: ["networking","messaging","marketing"]
summary: "People buy into ideas, not products"
---

Quick update on my end, only because so much of the work I've been doing has been going out and talking, listening, meeting, emailing.

If there was one skill that I've developed over this past month, it's been how to make a cleaner and more succinct pitch about Daivergent to anyone who will listen. I buy strongly into the six second elevator pitch from a blog post I read from [Rajesh Anandan](https://unreasonable.is/your-elevator-pitch-is-too-long/), one of the trailblazing industry leaders in this space. 30 seconds is enough time for someone's eyes to glaze over, lose interest, re-orient themselves, and then lose focus again before you finally wrap up your speech. Your point needs to be in the first sentence or it's over. I wish someone had knocked that into me earlier!

Through iteration, I've managed to get down to this: "Daivergent is a data services company that hires technically gifted adults with autism and disabilities to perform intensive, detail-oriented tasks." There's still further room for refinement, but getting to this pitch has been enough to get interest. Converting that interest into a work order and contract is the next step, and one that'll require strengthening my salesmanship and marketing muscles. I think all the time about how I need to recruit individuals with these skill sets, and it's something I'm going to focus more on over the course of this next month.

I am humbled by how helpful and responsive people have been, from those giving advice to procurement officers and prospective clients. It goes to show the incredible awareness of the immense potential in the population that Daivergent employs, as well as a demand for services that this population is uniquely capable of. I feel excited for these next few weeks as hiring continues and the first agreements for work come to fruition.